### ISSUE TITLE
-resourcePath additionalParam does not work, instead -resourceRootPath does the magic

### ISSUE THREAD

**Issue by aquarahul** [teamcarma/swagger-jaxrs-doclet#102]
Firstly, i am new to swagger and to this plugin. With its uniqueness of generating swaggger json files from existing javadoc comments, we are using it. That helped us big time, in not touching any of the existing files or adding any new annotations.

However, when i tried using -resourcePath <name> in my pom.xml, it reported javadoc error of unknown flag of "resourcePath". Well searching on existing issues here, i found someone reported to use -resourceRootPath. And yes, that worked perfectly to my expectation.

Hence, creating this issue to request for an update in the README manual, so that it may officially get listed there and others intending to use it, may refer from there.
And yes, if my javadoc error on usage of -resourcePath is unexpected, then please let me know. I will post build error snapshot then.

Thanks.

**Comment by conorroche** [comment]
@aquarahul thanks for spotting this, ive fixed the readme now.
