### ISSUE TITLE
Support for java 8 date types

### ISSUE THREAD

**Issue by OskarKjellin** [teamcarma/swagger-jaxrs-doclet#104]
I see you do support setting the old fashioned `java.util.Date` as a string with format of date. Would be nice to support some more of the java 8 date types such as `OffsetDateTime`, `LocalDate` and so forth.

**Comment by conorroche** [comment]
@OskarKjellin ive added support for java 8 date time types now

**Comment by OskarKjellin** [comment]
@conorroche Awesome! I'll try it out soon. One question though, when we upgrade to the latest version, the description per API disappears?

**Comment by conorroche** [comment]
@OskarKjellin i wasn't aware of that can you give me more details e.g. give me some example source of your resource and the generated json thats different? I do know there is an issue ive just noticed in terms of some endpoints of ours not getting documented which im looking into atm

**Comment by conorroche** [comment]
@OskarKjellin are you still having the problem you mentioned?

**Comment by conorroche** [comment]
closing as i believe fixed and no feedback
