### ISSUE TITLE
Ability to add additional params

### ISSUE THREAD

**Issue by adamdougal** [teamcarma/swagger-jaxrs-doclet#108]
I've currently got doclet setup and running great in a gradle-dropwizard application. 
However I have a couple of servlet/resource filters which require extra headers to be sent.
Traditionally in swagger you would add a @ApiImplicitParams annotation. 
Is there any way to achieve this using swagger-jaxrs-doclet?

**Comment by conorroche** [comment]
its not currently supported but i should have time to add it in the near future

**Comment by conorroche** [comment]
@adamdougal I have now added support for implicit params, take a look at the @implicitParam tag description in the readme, in the simple form you can add a javadoc tag like this:

@implicitParam p1|string|header

**Comment by conorroche** [comment]
@adamdougal did you check if this works ok for you? id like to close this if so.

**Comment by adamdougal** [comment]
Hey, really sorry, been away and completely forgot about this.

Just tried it out just now and works perfectly!

Thanks!
