### ISSUE TITLE
format Calendar field

### ISSUE THREAD

**Issue by rmpestano** [teamcarma/swagger-jaxrs-doclet#119]
Hi guys, 

how do I format a Calendar field?

In my application all Calendar fields are mapped to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)  but in my swagger spec all calendar fields are mapped. 

How can I tell swagger the date format I am using?

**Comment by conorroche** [comment]
@rmpestano ive just committed a fix to treat Calendar as string with format date-time, in swagger date-time is as  ISO 8601

**Comment by rmpestano** [comment]
great! thank you @conorroche

**Comment by rmpestano** [comment]
just tested trunk version and it is working great! 

When do you plan a new release?

**Comment by conorroche** [comment]
@rmpestano ive just released 1.x and 1.1.x versions that include this fix
