### ISSUE TITLE
Does not support jackson v1 JsonProperty

### ISSUE THREAD

**Issue by e99majo** [teamcarma/swagger-jaxrs-doclet#122]
The doclet does not support org.codehaus.jackson.annotate.JsonProperty and org.codehaus.jackson.annotate.JsonIgnore.

Also there is an issue with the "issue66Test" testcase. The code will generate an org.codehaus.jackson.map.JsonMappingException if executed, since there is a conflicting JsonProperty definition.

**Comment by conorroche** [comment]
@e99majo ive merged in your pull request, nice work thanks a lot.
