### ISSUE TITLE
Swagger codegen treating Response as a model

### ISSUE THREAD

**Issue by allenh** [teamcarma/swagger-jaxrs-doclet#124]
Swagger Codegen is treating Response as a model that should be provided by the JSON when it really should be a reference from javax.ws.rs.core.Response

Java code to be generated: https://gist.github.com/allenh/2089f4f29089d0f6ed84
Generate JSON code: https://gist.github.com/anonymous/5f9d1930d1749761602e

As I'm not entirely sure where the problem lies so I am wondering if anyone who is having this problem can shed some light on it.

Thank in advance!

**Comment by conorroche** [comment]
@allenh I'm not sure I understand, are you talking about swagger code gen or this doclet as they are separate projects. This project does not expand javax.ws.rs.core.Response as a model object as it would baloon the json, from an api documentation point of view it just tells the user they will get a response but there is no information on the actual json of the response.

This project DOES support documenting the real entity returned in the response, in your case the getAccountById and addAccount methods can have the @responseType com.blinco.api.AccountRow javadoc tag added to them to do that.

**Comment by JacksMyth** [comment]
Hey I've also stumbled into this. For cases where the is a reponse, the custom @responseType works great.

However, I have cases where the server does not return any data down, besides the http server code and perhaps some headers. In these cases, the controller method still returns Response but the response has no entity set on it. The api doc gets a type=Response and the js client that is generated is expecting a Response object, but there isn't one. In these cases, I'd like to use @responseType void or is there another way we can achieve this?
