### ISSUE TITLE
@implicitParam not working

### ISSUE THREAD

**Issue by gautampriya** [teamcarma/swagger-jaxrs-doclet#125]
Using ```@implicitParam paramName|fully.qualified.path.to.DataType|query``` on an operation does not add it to the method's ```query``` parameter in the generated swagger json. Neither does it generate the ```"models"``` entry for ```fully.qualified.path.to.DataType```.

Please advise if I am missing something?

**Comment by conorroche** [comment]
query parameters cannot be complex objects, it would need to be a body param so try

@implicitParam paramName|fully.qualified.path.to.DataType|body

**Comment by conorroche** [comment]
closing as afaik is not a bug, have revised the docs to explain the above
