### ISSUE TITLE
Input Model schema default value not populating

### ISSUE THREAD

**Issue by karjy01** [teamcarma/swagger-jaxrs-doclet#129]
Hi,

Can anyone please suggest me how can I populate default values in model schema?
I am using following maven configurations:
 `<doclet>com.carma.swagger.doclet.ServiceDoclet</doclet>`
         `<docletArtifact>`
                 `<groupId>com.carma</groupId>`
                 `<artifactId>swagger-doclet</artifactId>`
                 `<version>1.0.5</version>`

Annotation in the service class is like this:
    `@bodyType com.xyz.abc.InputModel`

InputModel 
    `public class InputModel {`
       ` private String status;`
        `private String id;`
        `private String path;`
   ` }`

Generated schema json:
  ` {`
        `"status": "",`
      `  "iD": "",`
       ` "path": ""`
 `   }`

Generated schema is correct in format but I am unable to display any default value for those elements.Please help me in getting this to work, I have tried using @defaultvalue to the variables in the InputModel class but it didn't work. 

Thanks
karjy01

**Comment by conorroche** [comment]
the default value javadoc tag is case sensitive so should be @defaultValue like this:

/**
	 * @defaultValue true
	 */
	boolean trueFieldTag;

note there is a testcase ValueConstraintsTest and associated  test model and json in fixtures.valueconstraints

**Comment by karjy01** [comment]
Hi conorroche,

Thanks for such a prompt response.
Now I am able to see "defaultValue" in the generated json files. But it is not reflecting in the swaggerUI.
When I change the "swagger-ui.js" with the latest version it is working fine, but with auto generated "swagger-ui.js" it is not working. 

I am currently using swagger-jaxrs-doclet version 1.0.5.
Is there any workaorund for this? Or do I need to use the latest version of swagger-jaxrs-doclet? 
We are using Java1.7.0 which I believe is not supported version for swagger-jaxrs-doclet 1.1.X.

Please let me know if I can get this working with swagger-jaxrs-doclet 1.0.5 ?

Thanks
karjy01

**Comment by conorroche** [comment]
i wasnt aware of an issue with the built in swagger ui, you can always use your own ui files and disabled the ones that come with the doclet using the skipUiFiles option. i wont have a chance to look into this for a while and will probably just upgrade to the latest ui prior to the next 1.0.x release which from what u say should work ok

**Comment by karjy01** [comment]
Thank You conorroche, for the time I will replace the swagger-ui.js manually and continue.

Thanks
karjy01

**Comment by karjy01** [comment]
Hi conorroche,

I am reopening this thread for another question regarding @defaultValue.

I have a requirement where one of the input model attribute is a String array and I want to display default array in swagger for this attribute. I am correctly using @defaultValue to show String values but is there a way so that I can show a default array also for e.g ["aaa","bbb","ccc"]?? 

Please let me know.

 Thanks
- Jyoti

**Comment by karjy01** [comment]
Can anyone please update me on this? I know defaultValue should always be a single value and array is not supported. But is there a way to generate the JSON with defaultValue as an array["X","Y"] ?

**Comment by conorroche** [comment]
@karjy01 you cannot have an array of default values, even if it was generated as an array a client would not understand it as not part of the swagger spec. You can however have an array of allowed values, which in swagger is called the enum field. The doclet up to now has supported sourcing the allowable values from an Enum class, and now ive just committed a fix to allow using the @allowableValues javadoc tag to define the allowed values

I think thats as much as is possible on this.
