### ISSUE TITLE
Plugin fails when ${basedir} contains a space for apiInfoFile

### ISSUE THREAD

**Issue by BVulaj** [teamcarma/swagger-jaxrs-doclet#41]
The `additionalparam` config will cause a build to fail if the `${basedir}` token contains a space.

```
<additionalparam> ...  -apiInfoFile ${basedir} /src/main/webapp/static/apidocs/apiinfo.json</additionalparam>
```

Where `${basedir}` is:
 
    C:\Users\User Name\workspace\myproject/src/main/webapp/static/apidocs/apiinfo.json

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:javadoc (generate-service-docs) on project myproject: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - javadoc: error - Illegal package name: "Name\workspace\my-project/src/main/webapp/static/apidocs/apiinfo.json"
```

**Comment by conorroche** [comment]
have you tried putting quotes around ${basedir}

**Comment by BVulaj** [comment]
Hey @conorroche - We have.  We see the same output.

**Comment by conorroche** [comment]
you sure -apiInfoFile '${basedir}/src/main/webapp/static/apidocs/apiinfo.json' doesnt work as something equivalent seems ok for me on mac

**Comment by BVulaj** [comment]
Let us try a few more things and we'll get back to you.  Thanks for trying it out.

**Comment by BVulaj** [comment]
Initial tests point this working under Linux, but not under Windows, FYI.

**Comment by conorroche** [comment]
ok, you are not getting a file not found error but the "Illegal package name" one right? il try on a windows box tomorrow at some stage

**Comment by BVulaj** [comment]
Yep, exactly as you see above.

**Comment by conorroche** [comment]
hrmm possibly a bug with the maven javadoc plugin, if you try other params with space in their values like -apiVersion '1 2' does that work? also have a go at newer versions of the maven javadoc plugin like 2.10.1

**Comment by BVulaj** [comment]
I think I've also found a related bug under Windows:

```
IllegalArgumentException: Path after -apiInfoFile (C:\dev\v\workspace\mywebapp\src\main\webapp\static\apidocs\dev♂workspace {...}\src\main\webapp\static\apidocs\apiinfo.json) is expected to be an existing file!
```

Using ${basedir} under Windows causes a directory with `\v` or any other recognized escape character causes odd results.  See: ♂ character in output.

Do you believe that this is still an issue with the javadoc plugin itself?

**Comment by conorroche** [comment]
the above error is raised by my code if it cant read the file with the path given.
the path for the option comes in as a string from com.sun.javadoc.RootDoc.options method so I think the corrupted path is either:

a) a bug with maven property substitution of the ${basedir} to check this try putting in the full path to the file such as c:\temp\apiinfo.json
b) a bug with the maven javadoc plugin
c) a bug with the option parsing of com.sun.javadoc.RootDoc
d) some file encoding issue such as the pom.xml not being utf-8 and possible bad characters in it

I won't have a chance to test on windows today but may have time tomorrow

**Comment by conorroche** [comment]
@BVulaj I have finally gotten around to getting a windows box setup and have gotten to the bottom of this issue.

The maven javadoc plugin requires backslashes in <additionalparam> to be double escaped
You should also use double and not single quotes.

So you can use an absolute path, for example this works:

<additionalparam>-apiVersion '1 2' -docBasePath /sps/apidocs -apiBasePath /sps -apiInfoFile 'c:\\Users\\carma\\test files\\apiinfo.txt'</additionalparam>

You cannot use any of the normal maven path related variables like ${baseDir} as these resolve to single slashes and if passed in with a ctrl character following it like v or c as you have found will be replaced. 

What I have now added as a workaround to this limitation with the maven javadoc plugin is support for file URI style paths so instead you can use the maven ${project.baseUri} variable and follow it with / separated dirs. So for example this will now work in the latest doclet snapshot:

<additionalparam>-apiVersion '1 2' -docBasePath /sps/apidocs -apiBasePath /sps -apiInfoFile "${project.baseUri}/src/main/space test2/apiinfo.json"</additionalparam>
						
Can you confirm if the above solves your issue?

**Comment by conorroche** [comment]
closing as I believe this has been resolved with the documented workarounds
