### ISSUE TITLE
Allow including of packages

### ISSUE THREAD

**Issue by tadhgpearson** [teamcarma/swagger-jaxrs-doclet#43]
As well as being able to exclude packages by prefix, it would be cool to be able to also include them. 

For example, I have one project that builds my server, taking other dependent projects (containing JAX-RS declarations) as distinct libraries and building them together into a single server.
Just as I have one server, I'd like to have one swagger portal for that server, but the doclet won't include any of the endpoints provided by my libraries because by default the packages containing the source are not listed in my packages file. I'd like to be able to manually include them so that when the doclet build occurs, these APIs will be added to my documentation.

Presumably I'd have to also ensure the source for these files ends up on my classpath too.

**Comment by conorroche** [comment]
Hi Tadhg,

We do something similar in Carma, the way we do it is to use the maven-dependency-plugin to pull in the source files from the other library e,g,:

<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
    	<execution>
            <id>unpack-client-sources</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.avego.carma</groupId>
                  <artifactId>carma-api-doc-client</artifactId>
                  <version>${project.version}</version>
                  <classifier>sources</classifier>
                  <type>jar</type>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.directory}/additional-sources
									</outputDirectory>
                  <includes>**/*.java</includes>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>

Then we use the build helper plugin to attach these additional source files

<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
    		<execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/additional-sources</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

The doclet should then be able to see the class files.

**Comment by conorroche** [comment]
closing as solution via maven has been described

**Comment by tadhgpearson** [comment]
Thanks Conor, however I haven't been able to get that working. Are you then running
> mvn javadoc:javadoc 
to complete the build?

**Comment by conorroche** [comment]
No assume you have 2 projects and thus 2 pom files, project A has the class files you want to include and project B has either no additional class files or has the main class files you want to be auto documented. You would add the above plugins to the project B pom and then run mvn install on project B which would auto run the javadoc plugin. here is an example of the a pom that does this:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.avego.carma</groupId>
    <artifactId>carma-api-doc</artifactId>
    <version>2.2001.0-SNAPSHOT</version>
  </parent>
  <groupId>com.avego.carma</groupId>
  <artifactId>carma-api-doc-swagger</artifactId>
  <version>2.2001.0-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>Carma API Doc Swagger Integration</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    
    <dependency>
      <groupId>com.avego.carma</groupId>
      <artifactId>carma-api-doc-client</artifactId>
      <version>${project.version}</version>
      <classifier>sources</classifier>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
       <groupId>com.wordnik</groupId>
       <artifactId>swagger-jaxrs_2.10</artifactId>
       <version>1.3.2</version>
    </dependency>
  </dependencies>
  <pluginRepositories>
    <pluginRepository>
      <id>codehaus-snapshot-repo</id>
      <name>Codehaus Snapshot Repo</name>
      <url>http://snapshots.repository.codehaus.org</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </pluginRepository>
  </pluginRepositories>
  <build>
  
  	
      <resources>
      <resource>
        <directory>${project.basedir}/src/main/swagger/ui</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/*</include>
        </includes>
        <targetPath>${project.build.directory}/swagger/ui</targetPath>
      </resource>
      <resource>
        <directory>${project.basedir}/src/main/swagger/includes</directory>
        <filtering>true</filtering>
        <includes>
          <include>*.json</include>
          <include>*.properties</include>
        </includes>
        <targetPath>${project.build.directory}/swagger/includes</targetPath>
      </resource>
    </resources>
  
    <finalName>${project.artifactId}-${project.version}</finalName>
    <plugins>
    	
    	<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>
      
      	<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>2.6</version>
          <configuration>
            <delimiters>
              <delimiter>${*}</delimiter>
            </delimiters>
            <useDefaultDelimiters>false</useDefaultDelimiters>
          </configuration>
        </plugin>
      
    	<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
    	<execution>
            <id>unpack-client-sources</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.avego.carma</groupId>
                  <artifactId>carma-api-doc-client</artifactId>
                  <version>${project.version}</version>
                  <classifier>sources</classifier>
                  <type>jar</type>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.directory}/additional-sources
									</outputDirectory>
                  <includes>**/*.java</includes>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
    	
    
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <configuration>
              <tasks>
                <jar destfile="target/${project.artifactId}-${project.version}.zip">
                  <zipfileset dir="${project.build.directory}/swagger/apidocs" includes="*.json" />
                  <zipfileset dir="${project.build.directory}/swagger/ui" includes="*.html,*.js,css/,images/,lib/" />
                </jar>
              </tasks>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          
          <execution>
            <id>attach-artifacts</id>
            <phase>package</phase>
            <goals>
              <goal>attach-artifact</goal>
            </goals>
            <configuration>
              <artifacts>
                <artifact>
                  <file>target/${project.artifactId}-${project.version}.zip</file>
                  <type>zip</type>
                </artifact>
              </artifacts>
            </configuration>
          </execution>	
    		<execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/additional-sources</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
          
        <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <executions>
                    <execution>
                        <id>generate-service-docs</id>
                        <phase>process-resources</phase>
                        <configuration>
                            <doclet>com.carma.swagger.doclet.ServiceDoclet</doclet>
                            <docletArtifact>
                                <groupId>com.carma</groupId>
                                <artifactId>swagger-doclet</artifactId>
                                <version>1.0.4.2</version>
                            </docletArtifact>
                            <reportOutputDirectory>${project.build.directory}/swagger</reportOutputDirectory>
                            <useStandardDocletOptions>false</useStandardDocletOptions>
                            <additionalparam>-sortResourcesByPriority -disableCopySwaggerUi -crossClassResources -apiVersion 1 -docBasePath ${swagger.doc.base.path} -apiBasePath /carmaapi -authOperationScopes rtr -apiAuthorizationsFile ${project.build.directory}/swagger/includes/apiauth.json -apiInfoFile ${project.build.directory}/swagger/includes/apiinfo.json -variablesPropertiesFile ${project.build.directory}/swagger/includes/vars.properties</additionalparam>
                        </configuration>
                        <goals>
                            <goal>javadoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
    </plugins>
  </build>
</project>

**Comment by conorroche** [comment]
@tadhgpearson i missed mentioning that the sources jar should be added as a dependency too, ive revised my original comment for that.
