### ISSUE TITLE
support wrapped types for paramaters e.g. Option<String>

### ISSUE THREAD

**Issue by aptogo** [teamcarma/swagger-jaxrs-doclet#47]
When using Dropwizard the types of input parameters declared for a resource method don't necessarily correspond with what you want to appear in the docs e.g.:

    @GET
    public Greeting sayHello(@QueryParam("name") Optional<String> name) {
        ...
    }

I'd like the `name` parameter to appear as the simple type 'string' in the docs, not `Optional`. The same goes for `LongParam` - I'd like that to appear as `long`.

Is the possible already or could you add something like a @paramType javadoc tag?

**Comment by conorroche** [comment]
this is possible using the genericWrapperTypes doclet option e.g. -genericWrapperTypes com.google.common.base.Optional

i will add this to the default set

**Comment by conorroche** [comment]
sorry the above is only applicable to response types not parameters so it will require a fix

**Comment by conorroche** [comment]
i have now committed a fix for this

**Comment by conorroche** [comment]
@aptogo can you confirm this is ok for you now in v 1.0.4?

**Comment by conorroche** [comment]
closing as I believe this has been resolved
