### ISSUE TITLE
Add support for javax.validation annotations (JSR-303) on DTOs

### ISSUE THREAD

**Issue by kozlovda** [teamcarma/swagger-jaxrs-doclet#51]
Hi Conor,

First of all thanks for the great doclet! :)

Now, working on a project I found out that I have to duplicate validation constraints in javadocs, although I've already defined them using [JSR-303 annotations](http://beanvalidation.org), e.g.:
```java
/**
 * User name, 3 - 256 characters long.
 */
@NotNull
@Size(min = 3, max = 256)
private String name;
```

So it would be nice if doclet could recognize those (at least default set).

Or at very least treat:
- `javax.validation.@NotNull` as `@mandatory` tag,
- `javax.validation.@Min` as `@min` tag,
- `javax.validation.@Max` as `@man` tag, and
- `javax.validation.@Size` as `minLength` and/or `maxLength` properties as defined in [swagger-spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) (no matching tags found in doclet docs).

Hope this makes sense!

### UPDATE
- fixed description

**Comment by deslauriersp** [comment]
+1 on this one

**Comment by conorroche** [comment]
yes thanks for the feedback, I will take a look at it, note that there are doclet tags for min/max e.g. @min 1 and @max 5

**Comment by conorroche** [comment]
i have now added support for this, @kozlovda can you confirm its now ok for you?

**Comment by conorroche** [comment]
Note i support these on model fields, model methods and also on resource method parameters, I also added support for the @Null and DecimalMin and DecimalMax annotations

**Comment by kozlovda** [comment]
Hi Conor, thanks a lot! I'll give it a try and let you know.

**Comment by conorroche** [comment]
closing as I believe this has been resolved

**Comment by OskarKjellin** [comment]
@conorroche Any plans on supporting this for parameters as well? I've set @Min(1) on my query parameter but it's not getting picked up when generating.
