### ISSUE TITLE
Model schema is incorrect when using custom JSON serialize/deserialize adapters

### ISSUE THREAD

**Issue by buzzkillington** [teamcarma/swagger-jaxrs-doclet#60]
My model includes a class that's a wrapper around a String, with a custom serializer and deserializer config at the class-level to write/read the wrapped String field; it's effectively:
```
@JsonSerialize(using = IdSerializer.class)
@JsonDeserialize(using = IdDeserializer.class)
public class IdWrapper {
	private String id;
	public IdWrapper (String id) {
		this.id = id;
	}
	
	public String getId() {
		return id;
	}
}
```
Whenever an object containing an IdWrapper gets serialized, the IdSerializer just writes out the ```id``` String value.  Unfortunately, swagger-jaxrs-doclet's Model Schema is showing the entire Wrapper object as an embedded object.  If I have:
```
public class MyObj {
	private IdWrapper myId;
	public IdWrapper getIdWrapper() {
		return myId;
	}
}
```
the actual custom-serialized output looks like: 
```
{
	"myId":""
}
```
but the generated Model Schema shows:
```
{
	"myId": {
		"id": ""
	}
}
```
How can I get swagger-jaxrs-doclet to generate the correct model schema in this case?

**Comment by conorroche** [comment]
@buzzkillington this can be done using the stringTypePrefixes doclet option

 e.g.  -stringTypePrefixes com.mypackage.IdWrapper 

where com.mypackage can be changed to the package of your id wrapper class

**Comment by buzzkillington** [comment]
@conorroche ok, thanks.  I'd worked around this in the meantime, but that's good to know for future use.
