### ISSUE TITLE
Order properties in model objects as ordered in source code

### ISSUE THREAD

**Issue by wrwatson** [teamcarma/swagger-jaxrs-doclet#67]
Let's say I have a model object with these properties:-
* Address1
* Address2
* City
* State
* ZipCode

For readability, I would like the properties in the JSON file to be ordered the same way in which they are ordered in the source code.

Currently, they appear to be ordered according to the HashMap iterator order.  This isn't guaranteed by java to be anything in particular.

(NB. In theory, JSON properties are unordered.  In practice, swagger-ui displays the model fields in the order in which they appear in the JSON.)

**Comment by conorroche** [comment]
@wrwatson i have just committed a fix for this now

**Comment by wrwatson** [comment]
Thanks @conorroche I'll check it out soon.

**Comment by conorroche** [comment]
closing as no response and I believe this has been fixed.
