### ISSUE TITLE
no more alphabetical ordering of services in shipped Swagger-UI

### ISSUE THREAD

**Issue by dwalden** [teamcarma/swagger-jaxrs-doclet#70]
Just a heads-up...

This applies to the HEAD of master of the swagger-jaxrs-doclet project, currently 2adb450c0e6594e1353d134aec306003c5561bf7.

It appears that the Swagger-UI that is shipped with this doclet does not sort the services alphabetically.

The HEAD of master of the **Swagger-UI project**, currently 198dd641b460e16f85b9bc5f69c46639878b8781, seems to work fine; the services are sorted.

This is not an urgent issue for me, I am currently just evaluating Swagger and I can use a standalone Swagger-UI instead of the one shipped with this doclet. 

Thanks.

**Comment by conorroche** [comment]
@dwalden do you know if swagger ui 2.1.0 has this issue? id prefer to ship a release version of the swagger ui with the doclet, note the doclet already supports the following sorting:

1) for ordering the resources in the resource listing it supports sorting by the path and/or by a priority value
2) for the endpoints within a resource it supports sorting them by path

you can add the -sortResourcesByPath option to the doclet

**Comment by dwalden** [comment]
Hi @conorroche , I haven't tried 2.1.0.

**Comment by conorroche** [comment]
ive upgraded the embedded ui to swagger 2.1.0 and it looks to be fixed, it may have been down to the sorter parameter in index.html changing to apisSorter or may have just been a bug with the 2.1.8-M1 ui version that was previously embedded
