### ISSUE TITLE
Model generation does not work properly in some cases 

### ISSUE THREAD

**Issue by cornelcreanga** [teamcarma/swagger-jaxrs-doclet#72]
Go on fixtures.collections.CollectionResource and comment everything except the last method.

```
	@POST
	@Path("/listofitems")
	public void setListOfItems(List<CollectionItem> items) {
	}
```

Check the generated model - the CollectionItem is missing. However If you add CollectionItem as a part of return type it will work (uncomment the getItems method). 

I should be able to check in a fix on Monday - unless you are already planning to do it.

**Comment by conorroche** [comment]
@cornelcreanga my fix for issue 71 should solve this, let me know if it works for you

**Comment by cornelcreanga** [comment]
Hi, 
I've checked and it works, thanks, I'll close the issue.
