### ISSUE TITLE
SuccessCode not being either set in JSON or being sent to UI

### ISSUE THREAD

**Issue by nkoterba** [teamcarma/swagger-jaxrs-doclet#77]
The Swagger UI looks for a data element `successCode` to show what status code the default success response belongs to:

![image](https://cloud.githubusercontent.com/assets/2508944/7829185/5a705142-03f3-11e5-95f5-a9b5ab800bc5.png)

It should look like this:
![image](https://cloud.githubusercontent.com/assets/2508944/7829194/6976efa2-03f3-11e5-8b41-cfeb1ff5230c.png)

The javascript in `swagger-ui.js` that tries to access the `successCode` parameter is:
```javascript
return "          <h4>Response Class (Status "
			+ escapeExpression(((helper = (helper = helpers.successCode || (depth0 != null ? depth0.successCode : depth0)) != null ? helper : helperMissing), (typeof helper === functionType ? helper.call(depth0,
				{
					"name": "successCode",
					"hash": {},
					"data": data
				}) : helper)))
			+ ")</h4>\n          <p><span class=\"model-signature\" /></p>\n          <br/>\n          <div class=\"response-content-type\" />\n";
```

Unfortunately, since successCode is not being set in the JSON and/or being correctly pulled in the Javascript, we get "blank" pages.

This can be seen on the current Sample DropDown demo.

**Comment by conorroche** [comment]
hrmm odd because swagger 1.2 doesnt use successCode that was part of the old 1.1 spec. Now it accepts

"responseMessages": [
            {
              "code": 400,
              "message": "Invalid ID supplied"
            },
            {
              "code": 404,
              "message": "Order not found"
            }
          ]

but the UI must not have been updated to look through the responseMessages array, I guess we could add back in successCode to the generated json but it feels wrong

**Comment by nkoterba** [comment]
@conorroche 

I've updated my `swagger-ui.js` to look through the responseMessages array and set the correct items based on the data now being sent back.  The `swagger-ui.js` file is rather cumbersome (I'm not a big fan of Backbone or Handlebars...much prefer Angular or Aurelia) so my edits are more "quick hacks" to get the UI to show up correctly.

Feel free to use and/or tweak the `swagger-ui.js` code that you bundle in the Doclet.

I replaced this code block in the original `swagger-ui.js`:
```javascript
if (this.model.successResponse) {
      successResponse = this.model.successResponse;
      for (key in successResponse) {
        value = successResponse[key];
        this.model.successCode = key;
        if (typeof value === 'object' && typeof value.createJSONSample === 'function') {
          signatureModel = {
            sampleJSON: JSON.stringify(value.createJSONSample(), void 0, 2),
            isParam: false,
            signature: value.getMockSignature()
          };
        }
      }
```

with this:
```javascript
this.model.responseMessages.forEach(function (response) {
			if (response.code >= 200 && response.code < 300) {
				successResponse = response;
			}
		});
		if (successResponse) {
			this.model.successCode = successResponse.code;
			// TODO: Not really sure what all this did below
			//for (key in successResponse) {
			//	value = successResponse[key];
			//	this.model.successCode = value;
			//	if (typeof value === 'object' && typeof value.createJSONSample === 'function') {
			//		signatureModel = {
			//			sampleJSON: JSON.stringify(value.createJSONSample(), void 0, 2),
			//			isParam: false,
			//			signature: value.getMockSignature()
			//		};
			//	}
			//}
```

**Comment by conorroche** [comment]
Ive now upgraded to swagger ui 2.1.0 as the embedded ui version and this issue has been resolved by it.
