### ISSUE TITLE
Provide `includeResourcePrefixes` Configuration Option

### ISSUE THREAD

**Issue by nkoterba** [teamcarma/swagger-jaxrs-doclet#80]
Currently, the project supports `excludeResourcePrefixes` configuration option. 

However, in our project we have lots of items we'd like to exclude and only a few we'd like to include.  Would be beneficial if instead of providing all the "exclusions", we could just provide the inclusions.

In a gradle task, this would look like:
```java
options.addStringOption("includeResourcePrefixes", "com.me.server.rest.api");
```

**Comment by conorroche** [comment]
@nkoterba I have now added support for includeResourcePrefixes to the master
