### ISSUE TITLE
Type identification does not work properly when mixing array types / regular types

### ISSUE THREAD

**Issue by cornelcreanga** [teamcarma/swagger-jaxrs-doclet#81]
Try to generate the Swagger model from the following class:

@Path("/arrays")
@SuppressWarnings("javadoc")
public class ArraysResource {

	@POST
	@Path("/arrayofstrings")
	public void setArrayOfStrings(String someString, String[] items) {
		// noop
	}
	@POST
	@Path("/arrayofstrings2")
	public void setArrayOfStrings2(String someString, String[] items) {
		// noop
	}
}

The 'someString' parameter from the second method will be identified as having the type 'array' instead of string. The issue is in AnnotationAwareTranslator.java file - the typeNameCache structure. After parsing the setArrayOfStrings method the cache will associate String -> array type and it will not resolve properly the parameter 'someString'. Let me know if you want more info.

Thanks.

**Comment by conorroche** [comment]
@cornelcreanga thanks for the detailed description of the issue made it easy to fix, ive applied a fix for this to the master now.
