### ISSUE TITLE
Java 8 tools.jar API Compatibility Issue

### ISSUE THREAD

**Issue by nkoterba** [teamcarma/swagger-jaxrs-doclet#83]
So I'm building/running this project from source versus downloading via Maven so I can tweak/update things to better fit our scenario.

However, the current source relies on Java 7 JavaDoc API specifications.  As far as I can tell the only API call in the current code base that is not Java 8 compatible is `RootDocLoader.java`'s call to `getRootDocImpl`.

An extra parameter has been added in Java 8 `tools.jar`'s getRootDocImpl method.

**Java 7 getRootDocImpl**
```java
public RootDocImpl getRootDocImpl(String var1, String var2, ModifierFilter var3, List<String> var4, List<String[]> var5, boolean var6, List<String> var7, List<String> var8, boolean var9, boolean var10, boolean var11) throws IOException {
```

**Java 8 getRootDocImpl**
```java
public RootDocImpl getRootDocImpl(String var1, String var2, ModifierFilter var3, List<String> var4, List<String[]> var5, Iterable<? extends JavaFileObject> var6, boolean var7, List<String> var8, List<String> var9, boolean var10, boolean var11, boolean var12) throws IOException
```

Thus, my system's Java version is Version 8 so when I try to use either a Maven `.pom` file or a Gradle `build.gradle` file and reference my JAVA_HOME's tools.jar, it pulls in Java 8 and fails compliation.

pom file:
```java
           <dependencies>
                <dependency>
                    <groupId>com.sun</groupId>
                    <artifactId>tools</artifactId>
                    <version>1.7.0</version>
                    <scope>system</scope>
                    <systemPath>${java.home}/../lib/tools.jar</systemPath>
                </dependency>
            </dependencies>
```

My gradle file:
```java
files("${System.properties['java.home']}/../lib/tools.jar")
```

Both the above, resolve to the following on my system:
```java
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/../lib/tools.jar
```

The way I was able to "overcome" this issue for now was to manually include `tools.jar` from Java 7.

In Gradle I do this by copying Java 7 tools.jar into a "lib" directory and adding the following to my compile dependencies:
```java
fileTree(dir: 'lib', include: '*.jar')
```

I'm not as familiar with Maven but I imagine there's a similar way to include a locally-based jar.

I'd rather not do this but if the Project source is updated to Java 8 APIs, then those building this package on Java 7 will get errors, etc.  So perhaps the best solution is to include `tools.jar` as a lib in this code repo? (not sure about licensing issues though) so that the correct version is always used when building the source.

**Comment by conorroche** [comment]
i would lean towards either making the minimum source compatibility java 8 (java 7 is end of life since april) or using reflection, there are some features of java 8 javadoc that would have been useful such as being able to directly get the type of an array, so my preference is to move to java 8 unless someone has a big issue with it?

**Comment by joepadmiraal** [comment]
No problem for me :)

**Comment by nkoterba** [comment]
@conorroche FYI...all I did was change this method in the `RootDocLoader.java` class and it compiled fine against Java 8:

```java
return javaDoc.getRootDocImpl(
			"", 
			null, 
			new ModifierFilter(ModifierFilter.ALL_ACCESS), 
			new ListBuffer<String>().toList(),
			new ListBuffer<String[]>().toList(),
			new ListBuffer<JavaFileObject>().toList(),
			false, 
			subPackages.toList(), 
			new ListBuffer<String>().toList(), 
			false, 
			false, 
			false);
```

Note the addition of `new ListBuffer<JavaFileObject>().toList(),` to the parameter list.

The pom.xml file should also, obviously be updated, to use 1.8 for the `tools.jar` lib.

Mine was always pulling in whatever was in `JAVA_HOME` which was always Java 8 (and what led to several hours and head scratching).

**Comment by Randgalt** [comment]
I wonder if some of the issues I'm having (no summaries, descriptions, etc.) are due to changes in Java 8: https://docs.oracle.com/javase/8/docs/technotes/guides/javadoc/doclet/transition-1.5docletapi.html

**Comment by conorroche** [comment]
@nkoterba whats the url for your fork again? im looking to merge in your gradle config and wanted to look at it

**Comment by nkoterba** [comment]
https://github.com/nkoterba/swagger-jaxrs-doclet

See the build.gradle file comments to see how I'm working around "java 7" tools.jar on a "java 8" installed machine.  I'm not a Gradle pro so perhaps there's a way to specifically call out the java 7 tools.jar on a system where both Java 7 and 8 are installed.

Furthermore, I'm only interested in swagger doclet, so that's the only directory where I have a build.gradle.  If you wanted "gradleify" the entire project, then you may want/need build.gradle files in the samples as well as a master build.gradle file in the root directory.

I haven't had a need for these yet b/c I'm not using any of the samples.

**Comment by conorroche** [comment]
@nkoterba the master branch (1.1.0-SNAPSHOT) has now been updated to work with java 8
