### ISSUE TITLE
private members should not be documented by default

### ISSUE THREAD

**Issue by dwalden** [teamcarma/swagger-jaxrs-doclet#85]
Hi, 
This issue was found on master, revision 4af5927fae4748f361b86fb98caf08ba9f4ddb45 at the time.

If I specify @XmlAccessorType(XmlAccessType.NONE), only members with the @XmlAttribute annotation are included in the json output, as expected.
Example: 
``` java
@XmlRootElement(name = "foo")
@XmlAccessorType(XmlAccessType.NONE)
public class OnlineDBDetailsResource {

    private String foo;
    private String bar;

    @XmlAttribute
    public String getFoo() {
        return foo;
    }
}
```
... results in this output:
``` json

    "foo" : {
      "id" : "foo",
      "properties" : {
        "foo" : {
          "type" : "string"
        }
      },
      "required" : [ "foo" ]
    }
```
But if I don't specify @XmlAccessorType(XmlAccessType.NONE), then ALL members are included.
Example:
``` java
@XmlRootElement(name = "foo")
//@XmlAccessorType(XmlAccessType.NONE)
public class OnlineDBDetailsResource {

    private String foo;
    private String bar;

    @XmlAttribute
    public String getFoo() {
        return foo;
    }
}
```
... results in this:
``` json

    "foo" : {
      "id" : "foo",
      "properties" : {
        "foo" : {
          "type" : "string"
        },
        "bar" : {
          "type" : "string"
        }
      },
      "required" : [ "foo", "bar" ]
    }
```
I think this behaviour is incorrect as the [JAXB spec] (http://docs.oracle.com/javase/7/docs/api/javax/xml/bind/annotation/XmlAccessorType.html) says:
>  By default, if @XmlAccessorType on a class is absent, and none of its super classes is annotated with @XmlAccessorType, then the following default on the class is assumed:
>
>   @XmlAccessorType(XmlAccessType.PUBLIC_MEMBER)
 
Although I appreciate there is a workaround which is to specify @XmlAccessorType(XmlAccessType.NONE), or @XmlAccessorType(XmlAccessType.PUBLIC_MEMBER), I am reluctant to do this as it means tweaking something that is currently working as per the spec.

Many thanks.

**Comment by conorroche** [comment]
as far as I can recall other users expected the opposite, e.g. if you dont specify then private fields will be included and they mark the fields to exclude individually e.g. using @XmlTransient or @hidden, to avoid breaking things for those people I have added a new flag you can set -defaultModelFieldsXmlAccessType which will give you the behaviour you expect. 
Can you check it out and tell me if its ok for you?

**Comment by dwalden** [comment]
Hi @conorroche, I'm happy with the proposed solution. I did a clone of this repo but looks like the change hasn't been made?
```
$ git log --max-count=1 master
commit 4af5927fae4748f361b86fb98caf08ba9f4ddb45
Merge: e971461 b715a1e
Author: Conor Roche <conoroche@gmail.com>
Date:   Fri May 29 08:40:07 2015 +0100
```

**Comment by conorroche** [comment]
@dwalden i hadnt pushed properly, I have done so now

**Comment by conorroche** [comment]
closing for 1.0.5 release
