### ISSUE TITLE
No description or extra tags

### ISSUE THREAD

**Issue by Randgalt** [teamcarma/swagger-jaxrs-doclet#91]
My api json files are getting generated correctly but the javadoc comments, @description tags etc. are not being recognized for some reason - i.e. no description, summary, etc. are added to the swagger json files.

Maven: 3.3.3
Java: 1.8.0
Swagger-Doclet: 1.0.4.2

E.g.

```java
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    /**
     * TODO
     *
     * You should document your APIs. It helps users
     * and is also used by the Swagger Console.
     *
     * @requiredParams param1
     *
     * @apiDescription hey there this is good.
     * @return a value
     */
    public String myApi() {
        try {
            return new ObjectMapper().writeValueAsString(attributes.getAttribute("example-property"));
        } catch (JsonProcessingException e) {
            throw new WebApplicationException(e);
        }
    }
```

test.json: https://gist.github.com/Randgalt/1f3baf6647f56d90ceb5
service.json: https://gist.github.com/Randgalt/2f8eecc27abfe3857b5a

**Comment by conorroche** [comment]
The annotations should come after the /** **/
