### ISSUE TITLE
JsonView on parameters ignored?

### ISSUE THREAD

**Issue by neich** [teamcarma/swagger-jaxrs-doclet#99]
Hi,

I'm trying to use JsonView for a parameter that represents the body of a POST request. While JsonView works great for return types, it ignores the view in the POST case. This is the method:

```
  /**
   * @summary Create a new user
   * @description Create a new user
   * @excludeParams asyncResponse
   */
  @POST
  public void create(@JsonView(User.View.Post.class) @Valid User user,
                     @Suspended final AsyncResponse asyncResponse) {

    userService.create(user)
        .subscribe(new DefaultRESTSubscriber<IdUUID>(asyncResponse));
  }
```

The swagger doc show all fields in body. Am I missing something ? Thanks in advance

**Comment by conorroche** [comment]
@neich this isnt supported at the moment, i should have time to work on it this weekend

**Comment by conorroche** [comment]
@neich I have just committed support for this, let me know if it works for you

**Comment by neich** [comment]
Thanks! Unfortunately we had to adopt another strategy and we are no longer using @JsonView. The main problem is that some fields of the same entity are required when POSTing but optional (or even no present) when GETing. Password is an example. For this to work, we need to have separate classes, one for POST and other for GET. That way, password is @Required in the POST version, but it does not exists in the GET version.

At least I have not found a way to make it work with a single class for all operations ...

**Comment by conorroche** [comment]
closing as i believe this is resolved and original raiser is not in position to confirm
